# SPDX-FileCopyrightText: 2025 Ryan Lahfa <ryan.lahfa@numerique.gouv.fr>
#
# SPDX-License-Identifier: MIT

dhcp: dnsmasq --no-daemon --interface=vmboot --dhcp-range=192.168.50.1,192.168.50.100,12h --port=0 --log-dhcp
pixiecore: pixiecore api --dhcp-no-bind http://localhost:8000/pixiecore
http-server: caddy run
nix-binary-cache: harmonia
